providers = ["node"]

[variables]
NODE_VERSION = "20"
PNPM_HOME="/app/.pnpm"
NIXPACKS_NODE_VERSION = "20"

[phases.install]
cmds = [
  "npm install -g corepack",
  "corepack enable",
  "corepack prepare pnpm@10.15.1 --activate", 
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]
