apiVersion: v1
kind: Namespace
metadata:
  name: xmtp-agents
---
# Only needed if a provisioner runs inside the cluster
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provisioner-sa
  namespace: xmtp-agents
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: provisioner-role
  namespace: xmtp-agents
rules:
  - apiGroups: [""]
    resources: ["secrets","pods","persistentvolumeclaims"]
    verbs: ["create","get","list","watch","delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create","get","list","watch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: provisioner-rb
  namespace: xmtp-agents
subjects:
  - kind: ServiceAccount
    name: provisioner-sa
    namespace: xmtp-agents
roleRef:
  kind: Role
  name: provisioner-role
  apiGroup: rbac.authorization.k8s.io


